### ISSUE TITLE
Tokeniza dados do cartão apenas em debug

### ISSUE THREAD

**Issue by juniorschroder** [juniorschroder/TesteAPIJunoReactNative#1]
services/juno.js - a tokenização dos dados do cartão ocorre apenas em modo de depuração, tanto em device quanto em simulador (iOS e Android) ao rodar sem a depuração a tokenização retorna um erro apontando pra uma determinada linha no bundle js da app.

**Comment by mauromouratopsapp** [comment]
Aparentemente o problema ocorre no window.crypto.subtle, acredito que em release a plataforma não ofereça o suporte necessário para a execução dele. 
Recomendo utilizar o direct-checkout-android e direct-checkout-ios, nestes a tokenização ocorre normalmente em release.

**Comment by juniorschroder** [comment]
@mauromouratopsapp Exatamente, na época estava fazendo os testes pois precisava integrar o gateway em um app de venda de ingressos que estava desenvolvendo, **window.crypto** existe apenas no browser, não é implementado dentro do RN. A solução que tinha chegado sem utilizar as libs nativas da juno foi o seguinte, como preciso disso apenas pra tokenizar coloquei um HTML com a função em JS pra realizar a tokenização no server junto com o site da plataforma que esta em https, e no app uma webview que existe lá so pra acessar esse html, que ai tera acesso a window.cripto, então chamo na webview a função js que faz a tokenização, e com o retorno dela sigo normal fazendo as request pra api da juno. Até hoje não tirei um tempo para atualizar esse repo aqui com a solução, vou tentar fazer isso nos proximos dias. Abraço
